[package]
name = "ashen_chronicle"
version = "0.38.1"
edition = "2021"

[profile.release]
codegen-units = 10
lto = true
opt-level = "s"
strip = true

[profile.test]
inherits = "release"
codegen-units = 256
opt-level = 3
strip = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
flate2 = "1.1"
crossterm = "0.29"
ratatui = "0.30.2"
