[package]
name = "ashen_chronicle"
version = "0.48.1"
edition = "2021"

[features]
bevy = ["dep:bevy"]

[profile.release]
codegen-units = 10
lto = true
opt-level = "s"
strip = true

[profile.test]
inherits = "release"
codegen-units = 256
opt-level = 3
strip = true

[dependencies]
bevy = { version = "0.19.1", optional = true, default-features = false, features = [
    "default_app",
    "2d_bevy_render",
    "ui_bevy_render",
    "std",
    "default_font",
    "bevy_winit",
    "x11",
    "android-game-activity",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
flate2 = "1.1"
crossterm = "0.29"
ratatui = "0.30.2"
