name: 🐞 Bug Report
description: File a bug/issue in a prettier format
title: "[BUG] ..."
labels: ["bug"]
assignees: ["right-ward"]
body:
- type: textarea
  attributes:
    label: Describe the Issue
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior (if possible).
    value: |
      1. ...
      2. ...
      3. ...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        OS: Ubuntu 20.04
        Version: latest (or a specific version)
    value: |
        - OS:
        - Version:
    render: bash
  validations:
    required: true
